### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Using Remix And MetaMask On Moonbeam

### ISSUE THREAD

**Issue by albertov19** [y12studio/helloworld-dot#1]
Hi y12studio,

Thanks for your participation in our challenge. Currently I'm having issues retrieving the three addresses stored in the contract. Could you please share the checkContract code that you used?

Thanks in advance

**Comment by y12studio** [comment]
Hi albertov19,

Thank you for your careful inspection. I found an wrong variable name error after checking the checkContract code. Is it acceptable to reissue a submission of https://github.com/PureStake/gitcoin-hello-world-by-moonbeam/issues/3 ?

Actual contract :
```
contract CheckContract {
   address public addressToken = 0x8ea7C370d4949AC1eEAB5F29ACE959Bc3c689578;
   address public account01 = 0xEBa7155d604Ba309805B4Aff27F5F1CD98eD8B1b;
   address public account02 = 0xCF780748b1a4001C6E43e399AFDA2614014AC437;
}
```

Expected contract:

```
contract CheckContract {
   address public addressToken = 0x8ea7C370d4949AC1eEAB5F29ACE959Bc3c689578;
   address public address1 = 0xEBa7155d604Ba309805B4Aff27F5F1CD98eD8B1b;
   address public address2 = 0xCF780748b1a4001C6E43e399AFDA2614014AC437;
}
```

**Comment by albertov19** [comment]
Yes, just redeploy the checkContract and let me know the address in here and I'll check. 
 ;)

**Comment by y12studio** [comment]
@albertov19  I have just redepolyed it at ```0xF6d3bb207eb0249d917DB5701c689f29a526b962``` . Please check for me when you have time.
